<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FoodsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'food_name' => 'Smoked Salmon Cannapes',
                'food_image' => 'food_images/smoked-cannapes.jpg',
                'food_type' => 'Food',
                'food_category' => 'Appetizer',
                'description' => 'Prepared salmon is paired with pumpernickel bread and spread with cheese, creme fraiche or sour cream. Lemon juice, lemon zest, horseradish, mustard, dill and capers are sprinkled on top.',
                'cost' => '70000',
            ],
            [
                'food_name' => 'Vol au Vent',
                'food_image' => 'food_images/vol-au-vent.jpg',
                'food_type' => 'Food',
                'food_category' => 'Appetizer',
                'description' => 'Soft puff pastry with sweet or savory fillings. The savory version is usually filled with minced chicken, breadcrumbs, mushrooms, and Madeira sauce.',
                'cost' => '50000',
            ],
            [
                'food_name' => 'Foei Gras',
                'food_image' => 'food_images/foei-gras.jpg',
                'food_type' => 'Food',
                'food_category' => 'Appetizer',
                'description' => 'The menu is made from selected duck or goose liver that offers a soft and buttery texture. ',
                'cost' => '45000',
            ],
            [
                'food_name' => 'Galette de Bretagne',
                'food_image' => 'food_images/galette-de-bretegne.jpg',
                'food_type' => 'Food',
                'food_category' => 'Appetizer',
                'description' => 'Crepe bretonne with a thin texture is wrapped with a filling consisting of various ingredients. The fillings include eggs, ham, mushrooms, and bacon.',
                'cost' => '30000',
            ],
            [
                'food_name' => 'Moules Farcies',
                'food_image' => 'food_images/moules-farcies.jpg',
                'food_type' => 'Food',
                'food_category' => 'Appetizer',
                'description' => 'A stuffed scallop dish that is grilled or broiled. Stuffed scallops are mixed with butter, parsley, garlic, shallots, black pepper, nutmeg, parmesan cheese, and breadcrumbs before baking.',
                'cost' => '45000',
            ],
            [
                'food_name' => 'Sea Bass with Apple, Fennel and Celery',
                'food_image' => 'food_images/sea-bass-apple-fennel-celery.jpeg',
                'food_type' => 'Food',
                'food_category' => 'Fish',
                'description' => 'This sea bass uses a delicious combination of seafood, including red prawns and scallops',
                'cost' => '85000',
            ],
            [
                'food_name' => 'Quick-Brined Salmon with Lemon, Miso, and Sofrito',
                'food_image' => 'food_images/quick-brined-salmon.jpg',
                'food_type' => 'Food',
                'food_category' => 'Fish',
                'description' => 'Green sofrito with garlic, shiro miso, butter, and lemon for a deeply flavorful sheet-pan salmon dinner. Brining the salmon before cooking it seasons the fish and prevents it from drying out.',
                'cost' => '115000',
            ],
            [
                'food_name' => 'Caraway Salmon with Rye Berry and Beet Salad',
                'food_image' => 'food_images/caraway-salmon.jpg',
                'food_type' => 'Food',
                'food_category' => 'Fish',
                'description' => 'Rye berries have a wonderfully aromatic, tangy flavor that goes well with the caraway in this Scandinavian-style dish from chef Marco Canora.',
                'cost' => '95000',
            ],
            [
                'food_name' => 'Miso Air Fryer Salmon with Baby Bok Choy',
                'food_image' => 'food_images/miso-air.jpg',
                'food_type' => 'Food',
                'food_category' => 'Fish',
                'description' => 'Cooking salmon in the air fryer allows the miso marinade to form a salty-sweet crust on the surface of each fillet. the edges of the leaves will char a bit, creating a savory contrast to the ginger, soy, and sesame oil sauce that goes on top.',
                'cost' => '110000',
            ],
            [
                'food_name' => 'Sizzling Garlic Salmon with Sheet Pan Potatoes',
                'food_image' => 'food_images/sizzling-garlic.jpg',
                'food_type' => "Food",
                'food_category' => 'Fish',
                'description' => "For this sheet pan dinner, baby potatoes, red onion, and spring onions get a head start in a hot oven before they're joined by a side of salmon that's been slathered with mustard and drizzled with toasted garlic oil. The salmon cooks alongside the vegetables for a seamless finish.",
                'cost' => '130000',
            ],
            [
                'food_name' => "Quick-Cured Salmon Steaks with Grilled Tomatoes and Tzatziki",
                'food_image' => "food_images/quick-cured-salmon.jpg",
                'food_type' => "Food",
                'food_category' => "Steak",
                'description' => "Salmon steaks are essentially two fillets attached by the spine of the fish. Less expensive and easier to grill than a fillet, these steaks are quickly dry-cured in brown sugar, salt, and smoked paprika.",
                'cost' => "200000",
            ],
            [
                'food_name' => "Striploin 200 G",
                'food_image' => "food_images/striploin-g.jpg",
                'food_type' => "Food",
                'food_category' => "Steak",
                'description' => "Mushed carrot, baby carrot grill, carrot pickles, yellow tomato cherry",
                'cost' => "300000",
            ],
            [
                'food_name' => "T Bone 425 G",
                'food_image' => "food_images/t-bone-g.jpg",
                'food_type' => "Food",
                'food_category' => "Steak",
                'description' => "T Bone 425 g of Austrian black angus served with one side order up on your choice with bread crumbs",
                'cost' => "850000",
            ],
            [
                'food_name' => "Tenderloin 150 G",
                'food_image' => "food_images/tenderloin.jpg",
                'food_type' => "Food",
                'food_category' => "Steak",
                'description' => "Herbs and garlic butter/ rosemary flavored olive oil / coconut oil BREAD CRUMB • GARLIC • PARSLEY",
                'cost' => "400000",
            ],
            [
                'food_name' => "Ribeye 300 G",
                'food_image' => "food_images/ribeye-steak.jpg",
                'food_type' => "Food",
                'food_category' => "Steak",
                'description' => "A cut of beef from the rib section, one of the nine primal cuts, and is prized for its tenderness and flavor.",
                'cost' => "750000",
            ],
            [
                'food_name' => "Pumpkin Cappucino Soup",
                'food_image' => "food_images/pumpkin-cappucino.jpg",
                'food_type' => "Food",
                'food_category' => "Soup",
                'description' => "Cream of roasted pumpkin with fresh herbs, garlic and onion, lemon whipped, lemon zest, served with toast",
                'cost' => "150000",
            ],
            [
                'food_name' => "Cauliflower Soup",
                'food_image' => "food_images/cauliflower-soup.jpg",
                'food_type' => "Food",
                'food_category' => "Soup",
                'description' => "Cauliflower, chicken stock, sour cream, cream cheese, cauliflower “croutons”, parmesan crumble",
                'cost' => "150000",
            ],
            [
                'food_name' => "Smoked Tomato Soup",
                'food_image' => "food_images/Smoked-Tomato-Soup.png",
                'food_type' => "Food",
                'food_category' => "Soup",
                'description' => "Smoked tomato cream soup, red bell pepper, herbs, basil gremolata and popcorn",
                'cost' => "150000",
            ],
            [
                'food_name' => "Fennel-Orange Salad",
                'food_image' => "food_images/fennel-orange.jpg",
                'food_type' => "Food",
                'food_category' => "Salad",
                'description' => "Thinly-sliced fennel ribbons (which have a licorice-like flavor) meet juicy orange wedges and briny fennel bulb",
                'cost' => "50000",
            ],
            [
                'food_name' => "Town Salad",
                'food_image' => "food_images/town-salad.jpg",
                'food_type' => "Food",
                'food_category' => "Salad",
                'description' => "ROCKET • GREEN APPLE • WALNUTS • SUNDRIED TOMATO PESTO",
                'cost' => "45000",
            ],
            [
                'food_name' => "Carrot Salad with Yogurt and Coriander",
                'food_image' => "food_images/carrot-salad.jpg",
                'food_type' => "Food",
                'food_category' => "Salad",
                'description' => "Evan and Sarah Rich of San Francisco's Rich Table shock the carrots in ice water after shaving to give them a wavy shape and slightly soften their crunch.",
                'cost' => "50000",
            ],
            [
                'food_name' => "Apple Walnut",
                'food_image' => "food_images/apple-walnut.jpeg",
                'food_type' => "Food",
                'food_category' => "Salad",
                'description' => "A nice and fresh salads made of Organic apple, fennel bulbs, Fresh basil leaves and 1/4 cup whole walnuts",
                'cost' => "47000",
            ],
            [
                'food_name' => "Lemon Cake",
                'food_image' => "food_images/lemon-cake.jpg",
                'food_type' => "Food",
                'food_category' => "Dessert",
                'description' => "Lemon cake, white chocolate, custard, sweet parmesan crumble, basil, lemon mousse, lemon zest",
                'cost' => "35000",
            ],
            [
                'food_name' => "Chocolate Brownie",
                'food_image' => "food_images/chocolate-brownie.jpg",
                'food_type' => "Food",
                'food_category' => "Dessert",
                'description' => "Chocolate brownie, chocolate crumble, meringue, blackberry, raspberry, dark chocolate, ice cream",
                'cost' => "30000",
            ],
            [
                'food_name' => "Barbecue Pinapple",
                'food_image' => "food_images/barbecue-pineapple.jpg",
                'food_type' => "Food",
                'food_category' => "Dessert",
                'description' => "Grilled smoked pineapple, Spiced (cinnamon and anise) Brown Sugar Syrup",
                'cost' => "32000",
            ],
            [
                'food_name' => "Date Cake",
                'food_image' => "food_images/date-cake.jpeg",
                'food_type' => "Food",
                'food_category' => "Dessert",
                'description' => "Date cake with jelly date, Arabic toffee, vanilla ice cream, gold leave",
                'cost' => "30000",
            ],
            [
                'food_name' => "Strawberry Millefeuille",
                'food_image' => "food_images/strawberr-mill.jpeg",
                'food_type' => "Food",
                'food_category' => "Dessert",
                'description' => "The crunch of the pastry with the smooth, rich filling – it’s pure decadence and lends itself well to any seasonal fruit. A strawberry millefeuille has always been on the menu at Pied à Terre in late spring/early summer.",
                'cost' => "75000",
            ],
            [
                'food_name' => "Lemon with Mint",
                'food_image' => "food_images/lemon-mint.jpg",
                'food_type' => "Drink",
                'food_category' => "Tea",
                'description' => "A herby and healthy drink made with fresh mint leaves, which is alkaline and helps to relieve you from the burning sensation in the throat.",
                'cost' => "15000",
            ],
            [
                'food_name' => "Ocha Tea",
                'food_image' => "food_images/ocha-tea.jpg",
                'food_type' => "Drink",
                'food_category' => "Tea",
                'description' => "Ocha which has a sepet taste when the tea tree is exposed to a lot of sun.",
                'cost' => "10000",
            ],
            [
                'food_name' => "Jasmine Tea",
                'food_image' => "food_images/jasmines-tea.jpg",
                'food_type' => "Drink",
                'food_category' => "Tea",
                'description' => "A delicate, fragrant, and floral flavor profile with sweet notes in the aftertaste.",
                'cost' => "15000",
            ],
            [
                'food_name' => "Black Tea",
                'food_image' => "food_images/black-tea.jpg",
                'food_type' => "Drink",
                'food_category' => "Tea",
                'description' => "Made from the leaves of a bush called Camellia sinensis with a flavor of malty, smoky, brisk, earthy, spiced, nutty, metallic, citrus, caramel, leather, fruity, sweet and honey.",
                'cost' => "12000",
            ],
            [
                'food_name' => "Blue Tea",
                'food_image' => "food_images/blue-tea.jpg",
                'food_type' => "Drink",
                'food_category' => "Tea",
                'description' => " An herbal infusion made by steeping butterfly pea flowers in hot water. Its high anthocyanin content gives the tea its characteristic bright blue color and medicinal properties.",
                'cost' => "17000",
            ],
            [
                'food_name' => "Americano",
                'food_image' => "food_images/americano.jpg",
                'food_type' => "Drink",
                'food_category' => "Coffee",
                'description' => "Made by pouring hot water over one or two espresso shots, resulting in a drink of similar volume and strength to regular coffee.",
                'cost' => "25000",
            ],
            [
                'food_name' => "Cappuccino",
                'food_image' => "food_images/cappucino.jpg",
                'food_type' => "Drink",
                'food_category' => "Coffee",
                'description' => "The perfect balance of espresso, steamed milk and foam.",
                'cost' => "26000",
            ],
            [
                'food_name' => "Dark Chocolate Mocha",
                'food_image' => "food_images/dark-chocolate-mocha.jpg",
                'food_type' => "Drink",
                'food_category' => "Coffee",
                'description' => "Made with a combination of 70% dark chocolate, cocoa powder, and freshly brewed espresso. The dark chocolate gives it a slightly thick consistency that makes this mocha extra delicious and indulgent.",
                'cost' => "30000",
            ],
            [
                'food_name' => "Espresso",
                'food_image' => "food_images/espresso.jpg",
                'food_type' => "Drink",
                'food_category' => "Coffee",
                'description' => "A concentrated form of coffee brewed with high pressure, hot water and finely ground coffee beans.",
                'cost' => "25000",
            ],
            [
                'food_name' => "African Coffee",
                'food_image' => "food_images/african-coffee.jpg",
                'food_type' => "Drink",
                'food_category' => "Coffee",
                'description' => "A drink that is aromatic but also packs a punch.",
                'cost' => "30000",
            ],
            [
                'food_name' => "Pineapple Juice",
                'food_image' => "food_images/pineapple-juice.jpg",
                'food_type' => "Drink",
                'food_category' => "Juice",
                'description' => "A juice made from pressing the natural liquid out from the pulp of the pineapple (a fruit from a tropical plant).",
                'cost' => "15000",
            ],
            [
                'food_name' => "Bloody Mary",
                'food_image' => "food_images/bloody-mary.jpg",
                'food_type' => "Drink",
                'food_category' => "Juice",
                'description' => "Tomato juice, Tabasco, salt , pepper, worcester sauce, celery.",
                'cost' => "30000",
            ],
            [
                'food_name' => "Orange Juice",
                'food_image' => "food_images/orange-juice.jpg",
                'food_type' => "Drink",
                'food_category' => "Juice",
                'description' => "A liquid extract of the orange tree fruit, produced by squeezing or reaming oranges.",
                'cost' => "15000",
            ],
            [
                'food_name' => "Strawberry Juice",
                'food_image' => "food_images/strawberry-juice.jpg",
                'food_type' => "Drink",
                'food_category' => "Juice",
                'description' => "A refreshing fresh fruit juice that is full of vitamin C and antioxidants and lot of invigorating flavor.",
                'cost' => "25000",
            ],
            [
                'food_name' => "Mango Juice",
                'food_image' => "food_images/mango-juice.jpg",
                'food_type' => "Drink",
                'food_category' => "Juice",
                'description' => "Slightly sweet, slightly tangy, and so perfect for helping you quench the thirst on hot summer days.",
                'cost' => "15000",
            ],
            [
                'food_name' => "Mojito Red Bull",
                'food_image' => "food_images/mojito-redbull.jpg",
                'food_type' => "Drink",
                'food_category' => "Mocktail",
                'description' => "In an old-fashioned glass, put the mint leaves, pineapple pieces, raw sugar and pour the lemon juice. Crush those ingredients with a muddler and fill your glass up with ice. Pour the rum and the pineapple juice, top it with the Red Bull.",
                'cost' => "35000",
            ],
            [
                'food_name' => "Strawberry Mojito",
                'food_image' => "food_images/strawberry-mojito.jpg",
                'food_type' => "Drink",
                'food_category' => "Mocktail",
                'description' => "Juiced limes into the pitcher along with mint, strawberries, and 1 cup sugar.",
                'cost' => "40000",
            ],
            [
                'food_name' => "Steak Town Mocktail",
                'food_image' => "food_images/steak-town-mojito.png",
                'food_type' => "Drink",
                'food_category' => "Mocktail",
                'description' => "Avocado, Passion Fruit syrup, Ice",
                'cost' => "45000",
            ],
            [
                'food_name' => "Passion Fruit Mojito",
                'food_image' => "food_images/passion-fruit.jpg",
                'food_type' => "Drink",
                'food_category' => "Mocktail",
                'description' => "Freshly muddled passion fruit, mint leaves, white rum and bubbly club soda, this twist on a classic Cuban cocktail tastes like summer in a glass.",
                'cost' => "40000",
            ],
            [
                'food_name' => "Vodka",
                'food_image' => "food_images/vodka.jpg",
                'food_type' => "Drink",
                'food_category' => "Alcohol",
                'description' => "A distilled alcoholic beverage (38% + ABV) made from grains or vegetables",
                'cost' => "90000",
            ],
            [
                'food_name' => "Margarita",
                'food_image' => "food_images/Margarita.jpg",
                'food_type' => "Drink",
                'food_category' => "Alcohol",
                'description' => "Sweet, sour, salty, bitter and umami, making it a perfectly balanced drink",
                'cost' => "55000",
            ],
            [
                'food_name' => "Cosmopolitan",
                'food_image' => "food_images/cosmopolitan.jpg",
                'food_type' => "Drink",
                'food_category' => "Alcohol",
                'description' => "A sharp, dry mixture of cranberry, lime and vodka with a gentle touch of sweet orange liqueur, this drink is classy and moreish.",
                'cost' => "65000",
            ],
            [
                'food_name' => "Daiquiri",
                'food_image' => "food_images/daiquiri.jpg",
                'food_type' => "Drink",
                'food_category' => "Alcohol",
                'description' => "A cocktail of rum, lemon or lime juice, and sugar, often with the addition of fruit and ice and mixed in an electric blender:a frozen banana daiquiri.",
                'cost' => "75000",
            ],
            [
                'food_name' => "Gimlet",
                'food_image' => "food_images/gimlet.jpg",
                'food_type' => "Drink",
                'food_category' => "Alcohol",
                'description' => "A drink consisting of sweetened lime juice and gin or vodka and sometimes carbonated or plain water.",
                'cost' => "85000",
            ],
        ];
        DB::table('foods')->insert($data);
    }
}
